name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily
  workflow_dispatch:

permissions:
  contents: write  # 👈 THIS line is critical to push to output branch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: Nqobile-Q
          outputs: |
            dist/github-snake.svg?speed=10
            dist/github-snake-dark.svg?palette=github-dark&speed=10

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


